### ISSUE TITLE
[feat] 크롬 익스텐션 대응 - 인증코드 발급 기능

### ISSUE THREAD

**Issue by EunjiShin** [pickly-team/pickly-backend#258]
### 배경
크롬 익스텐션에서 애플 로그인이 안되는 이슈에 대응하기 위함

### TO-DO
- [x] 로컬 캐시 설정 : TTL 5분
- [x] 인증코드 발급 API : 사용자에 매칭되는 값. 4글자
- [x] 인증코드 확인 API : 인증에 성공하면 캐시에서 삭제. response로 암호화된 PK값 전송

### 고려할 점
JWT 인증 필터 추가 이후 변경 예정
